# Generated by Django 3.2 on 2021-08-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('AndraPardesh', 'AndraPardesh'), ('Chandigarh', 'Chandigarh'), ('Delhi', 'Delhi'), ('Goa', 'Goa'), ('UP', 'UP'), ('Punjab', 'Punjab'), ('Haryana', 'Haryana')], max_length=50)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=50)),
                ('profile_img', models.ImageField(blank=True, upload_to='profileimg')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
